import random as r
hw=2
hw_part=4
for i in range(0,3):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write(str(r.randint(0,10)*10000))
        f.write('\n')
        f.write(str(r.randint(0,10)*1000))
        f.write('\n')
        start_y=r.randint(2000,2100)
        # end_y=r.randint(start_y+1,2150)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y+1))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')
for i in range(3,5):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write(str(r.randint(0,10)*10000))
        f.write('\n')
        f.write(str(r.randint(0,10)*1000))
        f.write('\n')
        start_y=r.randint(2000,2100)
        end_y=r.randint(start_y+1,2150)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(end_y))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')
for i in range(5,6):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write(str(r.randint(0,100000)))
        f.write('\n')
        f.write(str(r.randint(0,10000)))
        f.write('\n')
        start_y=r.randint(2000,2100)
        end_y=r.randint(start_y+1,2150)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(end_y))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')
for i in range(6,7):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write('0')
        f.write('\n')
        f.write(str(r.randint(0,10000)))
        f.write('\n')
        start_y=r.randint(2000,2100)
        end_y=r.randint(start_y+1,2150)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(end_y))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')
for i in range(7,8):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write('0')
        f.write('\n')
        f.write('0')
        f.write('\n')
        start_y=r.randint(2000,2100)
        end_y=r.randint(start_y+1,2150)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(end_y))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')
for i in range(8,9):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        negative=[1,1,1,1,1,1,1]
        negative[r.randint(0,6)]=-1
        f.write(str(r.randint(0,10)*10000*negative[0]))
        f.write('\n')
        f.write(str(r.randint(0,10)*1000*negative[1]))
        f.write('\n')
        start_y=r.randint(2000,2100)*negative[2]
        f.write(str(r.randint(1,12)*negative[3]))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)*negative[4]))
        f.write('\n')
        f.write(str(r.randint(start_y+1,2150)*negative[5]))
        f.write('\n')
        f.write(str(r.randint(1,20)*negative[6]))
        f.write('\n')
for i in range(9,10):
    with open('./0'+str(hw_part)+'/in/hw0'+str(hw)+'0'+str(hw_part)+'-'+str(i)+'.in', 'w') as f:
        f.write(str(r.randint(0,100000)))
        f.write('\n')
        f.write(str(r.randint(0,10000)))
        f.write('\n')
        start_y=r.randint(2000,2100)
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y))
        f.write('\n')
        f.write(str(r.randint(1,12)))
        f.write('\n')
        f.write(str(start_y-1))
        f.write('\n')
        f.write(str(r.randint(1,20)))
        f.write('\n')